params:
  epochs: 10
  batch_size: 32
  num_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000



artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plots
  plots_name : plot.jpg
  checkpoint_dir: checkpoint
  model_name: model.h5
  pickle_model_dir : pickle
  pickle_model_name : model.save


logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs